#!/usr/bin/env python3
"""
Portable IRIS Data Export - Environment-to-environment transfer files.

This module exports the IRIS registry, document metadata, document chunks, and
latest IRIS prompts from PostgreSQL into portable CSV and SQL artifacts. It is
intended for moving IRIS configuration and document retrieval data between
environments without copying generated identifiers or timestamps from the source
database.

Generated fields are intentionally omitted. During import, prompt IDs, document
UUIDs, chunk UUIDs, and timestamp columns are regenerated by PostgreSQL defaults.
Chunk rows are relinked to their regenerated document UUIDs by using the stable
document key pair of db_source and document_name.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from dataclasses import dataclass
from datetime import date, datetime, time
from decimal import Decimal
from pathlib import Path
from typing import Any, Iterable, Iterator, Sequence

import psycopg2
from psycopg2 import sql

try:
    from dotenv import load_dotenv

    load_dotenv()
    load_dotenv(".env.local", override=True)
except ImportError:
    pass


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_OUTPUT_ROOT = SCRIPT_DIR / "exports"
NULL_SENTINEL = r"\N"

REGISTRY_TABLE = "iris_database_registry"
METADATA_TABLE = "iris_document_metadata"
CHUNKS_TABLE = "iris_document_chunks"
PROMPTS_TABLE = "prompts"

REGISTRY_FILE = "iris_database_registry.csv"
METADATA_FILE = "iris_document_metadata.csv"
CHUNKS_FILE = "iris_document_chunks.csv"
PROMPTS_FILE = "iris_prompts_latest.csv"
INLINE_SQL_FILE = "iris_portable_import.sql"
CSV_IMPORT_SQL_FILE = "import_from_csv.sql"
README_FILE = "README.md"
MANIFEST_FILE = "manifest.json"
DIRECT_TABLE_CSV_DIR = "direct_table_csv"
DIRECT_UPLOAD_SQL_FILE = "after_direct_upload.sql"
IT_UPLOAD_CSV_DIR = "it_upload_csv"

GENERATED_COLUMNS = {
    REGISTRY_TABLE: {"created_at", "updated_at"},
    PROMPTS_TABLE: {"id", "created_at", "updated_at"},
    METADATA_TABLE: {"id", "created_at", "updated_at"},
    CHUNKS_TABLE: {"id", "document_id", "created_at", "updated_at"},
}

ARRAY_TYPE_CASTS = {
    "_text": "text[]",
    "_varchar": "character varying[]",
    "_bpchar": "character[]",
    "_int2": "smallint[]",
    "_int4": "integer[]",
    "_int8": "bigint[]",
    "_float4": "real[]",
    "_float8": "double precision[]",
    "_bool": "boolean[]",
    "_uuid": "uuid[]",
}


@dataclass(frozen=True)
class ColumnInfo:
    """PostgreSQL column metadata used to format portable export values."""

    name: str
    data_type: str
    udt_name: str
    character_maximum_length: int | None
    numeric_precision: int | None
    numeric_scale: int | None
    is_nullable: str
    column_default: str | None
    ordinal_position: int


def main() -> None:
    """Export portable IRIS data files.

    Returns:
        None.
    """
    args = _parse_args()
    settings = _connection_settings()
    output_dir = _resolve_output_dir(args.output_dir)

    print("Portable IRIS data export")
    print(f"  Host:     {settings['host']}")
    print(f"  Port:     {settings['port']}")
    print(f"  Database: {settings['database']}")
    print(f"  User:     {settings['user']}")

    try:
        conn = _get_connection(settings)
    except psycopg2.Error as exc:
        print(f"\nERROR: Could not connect to PostgreSQL: {exc}")
        sys.exit(1)

    try:
        table_columns = _load_export_columns(conn)
        export_plan = _build_export_plan(table_columns)

        if args.dry_run:
            _print_dry_run(conn, table_columns, export_plan)
            return

        output_dir.mkdir(parents=True, exist_ok=True)

        registry_rows = list(_iter_registry_rows(conn, export_plan[REGISTRY_TABLE]))
        prompt_rows = list(
            _iter_latest_iris_prompt_rows(conn, export_plan[PROMPTS_TABLE])
        )
        metadata_rows = list(_iter_metadata_rows(conn, export_plan[METADATA_TABLE]))

        print(f"\nWriting CSV exports to: {output_dir}")
        registry_count = _write_csv(
            output_dir / REGISTRY_FILE,
            _column_names(export_plan[REGISTRY_TABLE]),
            registry_rows,
            _column_map(export_plan[REGISTRY_TABLE]),
        )
        prompt_count = _write_csv(
            output_dir / PROMPTS_FILE,
            _column_names(export_plan[PROMPTS_TABLE]),
            prompt_rows,
            _column_map(export_plan[PROMPTS_TABLE]),
        )
        metadata_count = _write_csv(
            output_dir / METADATA_FILE,
            _column_names(export_plan[METADATA_TABLE]),
            metadata_rows,
            _column_map(export_plan[METADATA_TABLE]),
        )
        chunk_count = _write_csv(
            output_dir / CHUNKS_FILE,
            _chunk_csv_columns(export_plan[CHUNKS_TABLE]),
            _iter_chunk_rows(conn, export_plan[CHUNKS_TABLE]),
            _column_map(export_plan[CHUNKS_TABLE]),
        )

        direct_counts = _write_direct_table_csvs(output_dir, conn, table_columns)
        it_counts = _write_it_upload_csvs(
            output_dir,
            conn,
            table_columns,
            prompt_rows,
            export_plan[PROMPTS_TABLE],
        )

        print("\nWriting SQL import files")
        inline_chunk_count = _write_inline_sql(
            output_dir / INLINE_SQL_FILE,
            registry_rows,
            prompt_rows,
            metadata_rows,
            conn,
            export_plan,
        )
        _write_csv_import_sql(output_dir / CSV_IMPORT_SQL_FILE, export_plan)

        counts = {
            REGISTRY_TABLE: registry_count,
            PROMPTS_TABLE: prompt_count,
            METADATA_TABLE: metadata_count,
            CHUNKS_TABLE: chunk_count,
        }
        if inline_chunk_count != chunk_count:
            raise RuntimeError(
                "Chunk count mismatch between CSV and SQL export: "
                f"{chunk_count} CSV rows vs {inline_chunk_count} SQL rows"
            )

        _write_manifest(
            output_dir / MANIFEST_FILE,
            settings,
            table_columns,
            export_plan,
            counts,
            direct_counts,
            it_counts,
        )
        _write_readme(output_dir / README_FILE, counts, direct_counts, it_counts)

        print("\nExport complete")
        print(f"  Output: {output_dir}")
        print(f"  Registry rows: {registry_count}")
        print(f"  Latest IRIS prompts: {prompt_count}")
        print(f"  Document metadata rows: {metadata_count}")
        print(f"  Document chunk rows: {chunk_count}")
        print(f"  IT upload CSV directory: {output_dir / IT_UPLOAD_CSV_DIR}")
        print(f"  Direct CSV directory: {output_dir / DIRECT_TABLE_CSV_DIR}")
    finally:
        conn.close()


def _parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Export portable IRIS registry, document data, and latest prompts "
            "to CSV and SQL files."
        )
    )
    parser.add_argument(
        "--output-dir",
        help=(
            "Directory for export files. Defaults to "
            "db_config/exports/iris_portable_<timestamp>."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Connect and show export counts without writing files.",
    )
    return parser.parse_args()


def _connection_settings() -> dict[str, str]:
    """Return PostgreSQL connection settings from environment variables."""
    return {
        "host": os.getenv("VECTOR_POSTGRES_DB_HOST", "localhost"),
        "port": os.getenv("VECTOR_POSTGRES_DB_PORT", "34532"),
        "database": os.getenv("VECTOR_POSTGRES_DB_NAME", "maven-finance"),
        "user": os.getenv("VECTOR_POSTGRES_DB_USERNAME", os.getenv("USER", "postgres")),
        "password": os.getenv("VECTOR_POSTGRES_DB_PASSWORD", ""),
        "gssencmode": os.getenv("PGGSSENCMODE", ""),
        "sslmode": os.getenv("PGSSLMODE", ""),
    }


def _resolve_output_dir(output_dir: str | None) -> Path:
    """Resolve the output directory for generated export files."""
    if output_dir:
        return Path(output_dir).expanduser().resolve()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return DEFAULT_OUTPUT_ROOT / f"iris_portable_{timestamp}"


def _get_connection(settings: dict[str, str]):
    """Create a PostgreSQL connection from normalized settings."""
    kwargs: dict[str, Any] = {
        "host": settings["host"],
        "port": settings["port"],
        "database": settings["database"],
        "user": settings["user"],
        "password": settings["password"],
    }
    if settings["gssencmode"]:
        kwargs["gssencmode"] = settings["gssencmode"]
    if settings["sslmode"]:
        kwargs["sslmode"] = settings["sslmode"]
    return psycopg2.connect(**kwargs)


def _load_export_columns(conn) -> dict[str, list[ColumnInfo]]:
    """Load exportable column metadata for all required tables."""
    return {
        REGISTRY_TABLE: _fetch_table_columns(conn, REGISTRY_TABLE),
        PROMPTS_TABLE: _fetch_table_columns(conn, PROMPTS_TABLE),
        METADATA_TABLE: _fetch_table_columns(conn, METADATA_TABLE),
        CHUNKS_TABLE: _fetch_table_columns(conn, CHUNKS_TABLE),
    }


def _fetch_table_columns(conn, table_name: str) -> list[ColumnInfo]:
    """Fetch ordered PostgreSQL column metadata for a table."""
    query = """
        SELECT
            column_name,
            data_type,
            udt_name,
            character_maximum_length,
            numeric_precision,
            numeric_scale,
            is_nullable,
            column_default,
            ordinal_position
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
        ORDER BY ordinal_position
    """
    with conn.cursor() as cur:
        cur.execute(query, (table_name,))
        rows = cur.fetchall()

    if not rows:
        raise RuntimeError(f"Table not found or has no columns: {table_name}")

    return [
        ColumnInfo(
            name=row[0],
            data_type=row[1],
            udt_name=row[2],
            character_maximum_length=row[3],
            numeric_precision=row[4],
            numeric_scale=row[5],
            is_nullable=row[6],
            column_default=row[7],
            ordinal_position=row[8],
        )
        for row in rows
    ]


def _build_export_plan(
    table_columns: dict[str, list[ColumnInfo]],
) -> dict[str, list[ColumnInfo]]:
    """Remove generated columns and validate required import keys."""
    plan: dict[str, list[ColumnInfo]] = {}
    for table_name, columns in table_columns.items():
        excluded = GENERATED_COLUMNS[table_name]
        plan[table_name] = [column for column in columns if column.name not in excluded]

    _require_columns(plan[REGISTRY_TABLE], ["db_source"], REGISTRY_TABLE)
    _require_columns(
        plan[PROMPTS_TABLE],
        ["model", "layer", "name", "version"],
        PROMPTS_TABLE,
    )
    _require_columns(
        plan[METADATA_TABLE],
        ["db_source", "document_name"],
        METADATA_TABLE,
    )
    _require_columns(plan[CHUNKS_TABLE], ["db_source", "chunk_number"], CHUNKS_TABLE)
    return plan


def _require_columns(
    columns: Sequence[ColumnInfo],
    required_names: Sequence[str],
    table_name: str,
) -> None:
    """Raise if an expected import key is missing from the export plan."""
    names = {column.name for column in columns}
    missing = [name for name in required_names if name not in names]
    if missing:
        raise RuntimeError(f"{table_name} is missing required columns: {missing}")


def _print_dry_run(
    conn,
    table_columns: dict[str, list[ColumnInfo]],
    export_plan: dict[str, list[ColumnInfo]],
) -> None:
    """Print counts and generated-field handling without writing files."""
    registry_count = _fetch_count(conn, REGISTRY_TABLE)
    metadata_count = _fetch_count(conn, METADATA_TABLE)
    chunk_count = _fetch_count(conn, CHUNKS_TABLE)
    prompt_count = _fetch_latest_iris_prompt_count(conn)

    print("\nDry run")
    print(f"  {REGISTRY_TABLE}: {registry_count} rows")
    print(f"  latest iris prompts: {prompt_count} rows")
    print(f"  {METADATA_TABLE}: {metadata_count} rows")
    print(f"  {CHUNKS_TABLE}: {chunk_count} rows")
    print("\nGenerated columns omitted from exports")
    for table_name, excluded in GENERATED_COLUMNS.items():
        actual_columns = set(_column_names(table_columns[table_name]))
        omitted = sorted(excluded & actual_columns)
        print(f"  {table_name}: {', '.join(omitted)}")


def _fetch_count(conn, table_name: str) -> int:
    """Fetch a row count for a required table."""
    query = sql.SQL("SELECT COUNT(*) FROM {table}").format(
        table=sql.Identifier(table_name)
    )
    with conn.cursor() as cur:
        cur.execute(query)
        return int(cur.fetchone()[0])


def _fetch_latest_iris_prompt_count(conn) -> int:
    """Count latest-version prompt rows for model iris."""
    query = """
        SELECT COUNT(*)
        FROM (
            SELECT DISTINCT ON (layer, name) layer, name
            FROM prompts
            WHERE model = 'iris'
            ORDER BY layer, name, version DESC, updated_at DESC NULLS LAST
        ) latest_prompts
    """
    with conn.cursor() as cur:
        cur.execute(query)
        return int(cur.fetchone()[0])


def _iter_registry_rows(
    conn,
    columns: Sequence[ColumnInfo],
) -> Iterator[dict[str, Any]]:
    """Yield registry rows in stable db_source order."""
    query = _table_select_query(REGISTRY_TABLE, "r", columns, ["db_source"])
    yield from _iter_query(conn, query, _column_names(columns), "registry_export")


def _iter_latest_iris_prompt_rows(
    conn,
    columns: Sequence[ColumnInfo],
) -> Iterator[dict[str, Any]]:
    """Yield latest-version IRIS prompt rows using the application ordering rule."""
    query = sql.SQL(
        """
        SELECT DISTINCT ON (p.layer, p.name)
            {columns}
        FROM {table} p
        WHERE p.model = 'iris'
        ORDER BY
            p.layer,
            p.name,
            p.version DESC,
            p.updated_at DESC NULLS LAST,
            p.created_at DESC NULLS LAST
        """
    ).format(
        columns=_select_list("p", columns),
        table=sql.Identifier(PROMPTS_TABLE),
    )
    yield from _iter_query(conn, query, _column_names(columns), "prompts_export")


def _iter_metadata_rows(
    conn,
    columns: Sequence[ColumnInfo],
) -> Iterator[dict[str, Any]]:
    """Yield document metadata rows in stable document key order."""
    query = _table_select_query(
        METADATA_TABLE,
        "m",
        columns,
        ["db_source", "document_name"],
    )
    yield from _iter_query(conn, query, _column_names(columns), "metadata_export")


def _iter_chunk_rows(
    conn,
    columns: Sequence[ColumnInfo],
) -> Iterator[dict[str, Any]]:
    """Yield chunk rows with document natural keys for regenerated UUID mapping."""
    query = sql.SQL(
        """
        SELECT
            m.db_source AS document_db_source,
            m.document_name AS document_name,
            {chunk_columns}
        FROM {chunks_table} c
        JOIN {metadata_table} m ON m.id = c.document_id
        ORDER BY
            c.db_source,
            m.document_name,
            c.chunk_number,
            c.page_number,
            c.id
        """
    ).format(
        chunk_columns=_select_list("c", columns),
        chunks_table=sql.Identifier(CHUNKS_TABLE),
        metadata_table=sql.Identifier(METADATA_TABLE),
    )
    result_columns = _chunk_csv_columns(columns)
    yield from _iter_query(conn, query, result_columns, "chunks_export")


def _iter_direct_chunk_rows(
    conn,
    columns: Sequence[ColumnInfo],
) -> Iterator[dict[str, Any]]:
    """Yield direct chunk rows preserving table UUID columns."""
    query = _table_select_query(
        CHUNKS_TABLE,
        "c",
        columns,
        ["document_id", "chunk_number", "page_number", "id"],
    )
    yield from _iter_query(conn, query, _column_names(columns), "direct_chunks_export")


def _table_select_query(
    table_name: str,
    alias: str,
    columns: Sequence[ColumnInfo],
    order_columns: Sequence[str],
) -> sql.Composed:
    """Build a typed SELECT query for table export."""
    order_by = sql.SQL(", ").join(
        sql.SQL("{}.{}").format(sql.Identifier(alias), sql.Identifier(column_name))
        for column_name in order_columns
    )
    return sql.SQL("SELECT {columns} FROM {table} {alias} ORDER BY {order_by}").format(
        columns=_select_list(alias, columns),
        table=sql.Identifier(table_name),
        alias=sql.Identifier(alias),
        order_by=order_by,
    )


def _select_list(alias: str, columns: Sequence[ColumnInfo]) -> sql.Composed:
    """Build a SELECT list, casting vector columns to text for psycopg2."""
    expressions = []
    for column in columns:
        identifier = sql.SQL("{}.{}").format(
            sql.Identifier(alias),
            sql.Identifier(column.name),
        )
        if _is_vector_column(column):
            expressions.append(
                sql.SQL("{}::text AS {}").format(
                    identifier, sql.Identifier(column.name)
                )
            )
        else:
            expressions.append(identifier)
    return sql.SQL(", ").join(expressions)


def _iter_query(
    conn,
    query: sql.Composed,
    result_columns: Sequence[str],
    cursor_name: str,
) -> Iterator[dict[str, Any]]:
    """Stream query rows as dictionaries."""
    with conn.cursor(name=cursor_name) as cur:
        cur.itersize = 1000
        cur.execute(query)
        for record in cur:
            yield {column: value for column, value in zip(result_columns, record)}


def _write_csv(
    path: Path,
    columns: Sequence[str],
    rows: Iterable[dict[str, Any]],
    column_info: dict[str, ColumnInfo],
    null_value: str = NULL_SENTINEL,
) -> int:
    """Write rows to a CSV file using the configured NULL representation."""
    count = 0
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(columns)
        for row in rows:
            writer.writerow(
                [
                    _format_csv_value(
                        row.get(column),
                        column_info.get(column),
                        null_value=null_value,
                    )
                    for column in columns
                ]
            )
            count += 1
    print(f"  {path.name}: {count} rows")
    return count


def _write_direct_table_csvs(
    output_dir: Path,
    conn,
    table_columns: dict[str, list[ColumnInfo]],
) -> dict[str, int]:
    """Write exact table-shaped CSVs for direct table-by-table uploads."""
    direct_dir = output_dir / DIRECT_TABLE_CSV_DIR
    direct_dir.mkdir(parents=True, exist_ok=True)

    print(f"\nWriting direct table CSV exports to: {direct_dir}")
    registry_count = _write_csv(
        direct_dir / REGISTRY_FILE,
        _column_names(table_columns[REGISTRY_TABLE]),
        _iter_registry_rows(conn, table_columns[REGISTRY_TABLE]),
        _column_map(table_columns[REGISTRY_TABLE]),
    )
    prompt_count = _write_csv(
        direct_dir / PROMPTS_FILE,
        _column_names(table_columns[PROMPTS_TABLE]),
        _iter_latest_iris_prompt_rows(conn, table_columns[PROMPTS_TABLE]),
        _column_map(table_columns[PROMPTS_TABLE]),
    )
    metadata_count = _write_csv(
        direct_dir / METADATA_FILE,
        _column_names(table_columns[METADATA_TABLE]),
        _iter_metadata_rows(conn, table_columns[METADATA_TABLE]),
        _column_map(table_columns[METADATA_TABLE]),
    )
    chunk_count = _write_csv(
        direct_dir / CHUNKS_FILE,
        _column_names(table_columns[CHUNKS_TABLE]),
        _iter_direct_chunk_rows(conn, table_columns[CHUNKS_TABLE]),
        _column_map(table_columns[CHUNKS_TABLE]),
    )
    _write_direct_upload_sql(direct_dir / DIRECT_UPLOAD_SQL_FILE)
    return {
        REGISTRY_TABLE: registry_count,
        PROMPTS_TABLE: prompt_count,
        METADATA_TABLE: metadata_count,
        CHUNKS_TABLE: chunk_count,
    }


def _write_it_upload_csvs(
    output_dir: Path,
    conn,
    table_columns: dict[str, list[ColumnInfo]],
    prompt_rows: Sequence[dict[str, Any]],
    prompt_columns: Sequence[ColumnInfo],
) -> dict[str, int]:
    """Write the CSV bundle expected by IT's truncate/load process."""
    it_dir = output_dir / IT_UPLOAD_CSV_DIR
    it_dir.mkdir(parents=True, exist_ok=True)

    print(f"\nWriting IT upload CSV exports to: {it_dir}")
    registry_count = _write_csv(
        it_dir / REGISTRY_FILE,
        _column_names(table_columns[REGISTRY_TABLE]),
        _iter_registry_rows(conn, table_columns[REGISTRY_TABLE]),
        _column_map(table_columns[REGISTRY_TABLE]),
        null_value="",
    )
    prompt_count = _write_csv(
        it_dir / PROMPTS_FILE,
        _column_names(prompt_columns),
        prompt_rows,
        _column_map(prompt_columns),
        null_value="",
    )
    metadata_count = _write_csv(
        it_dir / METADATA_FILE,
        _column_names(table_columns[METADATA_TABLE]),
        _iter_metadata_rows(conn, table_columns[METADATA_TABLE]),
        _column_map(table_columns[METADATA_TABLE]),
        null_value="",
    )
    chunk_count = _write_csv(
        it_dir / CHUNKS_FILE,
        _column_names(table_columns[CHUNKS_TABLE]),
        _iter_direct_chunk_rows(conn, table_columns[CHUNKS_TABLE]),
        _column_map(table_columns[CHUNKS_TABLE]),
        null_value="",
    )
    _write_it_upload_readme(
        it_dir / README_FILE,
        {
            REGISTRY_TABLE: registry_count,
            PROMPTS_TABLE: prompt_count,
            METADATA_TABLE: metadata_count,
            CHUNKS_TABLE: chunk_count,
        },
    )
    return {
        REGISTRY_TABLE: registry_count,
        PROMPTS_TABLE: prompt_count,
        METADATA_TABLE: metadata_count,
        CHUNKS_TABLE: chunk_count,
    }


def _write_inline_sql(
    path: Path,
    registry_rows: Sequence[dict[str, Any]],
    prompt_rows: Sequence[dict[str, Any]],
    metadata_rows: Sequence[dict[str, Any]],
    conn,
    export_plan: dict[str, list[ColumnInfo]],
) -> int:
    """Write a self-contained SQL import file with regenerated generated fields."""
    registry_columns = _column_names(export_plan[REGISTRY_TABLE])
    prompt_columns = _column_names(export_plan[PROMPTS_TABLE])
    metadata_columns = _column_names(export_plan[METADATA_TABLE])
    chunk_columns = _column_names(export_plan[CHUNKS_TABLE])

    registry_info = _column_map(export_plan[REGISTRY_TABLE])
    prompt_info = _column_map(export_plan[PROMPTS_TABLE])
    metadata_info = _column_map(export_plan[METADATA_TABLE])
    chunk_info = _column_map(export_plan[CHUNKS_TABLE])

    chunk_count = 0
    with path.open("w", encoding="utf-8") as handle:
        _write_sql_header(handle, "Portable IRIS direct SQL import")
        handle.write("BEGIN;\n\n")

        handle.write("-- Registry rows are upserted by natural key: db_source.\n")
        for row in registry_rows:
            _write_upsert_values(
                handle,
                REGISTRY_TABLE,
                registry_columns,
                row,
                registry_info,
                ["db_source"],
                touch_updated_at=True,
            )

        handle.write("-- Latest IRIS prompts replace target model='iris' prompts.\n")
        handle.write(
            f"DELETE FROM {_ident(PROMPTS_TABLE)} WHERE {_ident('model')} = 'iris';\n\n"
        )
        for row in prompt_rows:
            _write_insert_values(
                handle, PROMPTS_TABLE, prompt_columns, row, prompt_info
            )

        _write_document_replacement_preamble(handle, metadata_rows)

        handle.write(
            "-- Document metadata rows regenerate id, created_at, and updated_at.\n"
        )
        for row in metadata_rows:
            _write_insert_values(
                handle,
                METADATA_TABLE,
                metadata_columns,
                row,
                metadata_info,
            )

        _write_document_presence_check(handle)

        handle.write(
            "-- Chunk rows regenerate id and created_at, and document_id is relinked.\n"
        )
        for row in _iter_chunk_rows(conn, export_plan[CHUNKS_TABLE]):
            _write_chunk_insert_select(handle, chunk_columns, row, chunk_info)
            chunk_count += 1

        handle.write("COMMIT;\n")
        handle.write(f"\n-- Imported {chunk_count} document chunk rows.\n")

    print(f"  {path.name}: direct SQL import")
    return chunk_count


def _write_csv_import_sql(
    path: Path,
    export_plan: dict[str, list[ColumnInfo]],
) -> None:
    """Write a psql loader that imports the generated CSV files through staging tables."""
    registry_columns = _column_names(export_plan[REGISTRY_TABLE])
    prompt_columns = _column_names(export_plan[PROMPTS_TABLE])
    metadata_columns = _column_names(export_plan[METADATA_TABLE])
    chunk_columns = _column_names(export_plan[CHUNKS_TABLE])
    chunk_csv_columns = _chunk_csv_columns(export_plan[CHUNKS_TABLE])

    with path.open("w", encoding="utf-8") as handle:
        _write_sql_header(handle, "Portable IRIS CSV staging import")
        handle.write(
            "-- Run this file from the export directory with psql -f import_from_csv.sql.\n"
        )
        handle.write("BEGIN;\n\n")

        _write_stage_table_from_target(
            handle,
            "_iris_stage_registry",
            REGISTRY_TABLE,
            registry_columns,
        )
        _write_copy_command(
            handle, "_iris_stage_registry", registry_columns, REGISTRY_FILE
        )

        _write_stage_table_from_target(
            handle,
            "_iris_stage_prompts",
            PROMPTS_TABLE,
            prompt_columns,
        )
        _write_copy_command(handle, "_iris_stage_prompts", prompt_columns, PROMPTS_FILE)

        _write_stage_table_from_target(
            handle,
            "_iris_stage_metadata",
            METADATA_TABLE,
            metadata_columns,
        )
        _write_copy_command(
            handle, "_iris_stage_metadata", metadata_columns, METADATA_FILE
        )

        _write_chunk_stage_table(handle, chunk_columns)
        _write_copy_command(
            handle, "_iris_stage_chunks", chunk_csv_columns, CHUNKS_FILE
        )

        _write_registry_stage_upsert(handle, registry_columns)
        _write_prompt_stage_replace(handle, prompt_columns)
        _write_metadata_stage_replace(handle, metadata_columns)
        _write_chunk_stage_insert(handle, chunk_columns)

        handle.write("COMMIT;\n")

    print(f"  {path.name}: CSV staging import")


def _write_direct_upload_sql(path: Path) -> None:
    """Write optional cleanup SQL for direct CSV uploads that preserve prompt IDs."""
    with path.open("w", encoding="utf-8") as handle:
        handle.write(
            "-- =============================================================================\n"
        )
        handle.write("-- Post direct CSV upload maintenance\n")
        handle.write(
            "-- =============================================================================\n"
        )
        handle.write(f"-- Generated: {datetime.now().isoformat(timespec='seconds')}\n")
        handle.write(
            "-- Run after uploading direct_table_csv prompts with preserved IDs.\n"
        )
        handle.write(
            "-- =============================================================================\n\n"
        )
        handle.write(
            "SELECT setval(\n"
            "    'prompts_id_seq',\n"
            "    GREATEST(COALESCE((SELECT MAX(id) FROM prompts), 0), 1),\n"
            "    true\n"
            ");\n"
        )
    print(f"  {path.name}: direct upload maintenance SQL")


def _write_it_upload_readme(path: Path, counts: dict[str, int]) -> None:
    """Write instructions specific to the IT CSV handoff folder."""
    text = f"""# IT Upload CSV Bundle

Generated: {datetime.now().isoformat(timespec="seconds")}

This folder is the handoff set for IT's current process.

## Files

| File | Rows | Load mode |
|------|------|-----------|
| `{REGISTRY_FILE}` | {counts[REGISTRY_TABLE]} | Truncate/load `{REGISTRY_TABLE}` |
| `{METADATA_FILE}` | {counts[METADATA_TABLE]} | Truncate/load `{METADATA_TABLE}` |
| `{CHUNKS_FILE}` | {counts[CHUNKS_TABLE]} | Truncate/load `{CHUNKS_TABLE}` |
| `{PROMPTS_FILE}` | {counts[PROMPTS_TABLE]} | Manual prompt entry; no prompt IDs/timestamps |

## Load Order

If loading all three database tables into an empty/replaced target set:

1. Truncate `{CHUNKS_TABLE}`
2. Truncate `{METADATA_TABLE}`
3. Truncate `{REGISTRY_TABLE}`
4. Load `{REGISTRY_FILE}`
5. Load `{METADATA_FILE}`
6. Load `{CHUNKS_FILE}`

`{METADATA_FILE}` includes the source `id` UUIDs. `{CHUNKS_FILE}` includes both
chunk `id` UUIDs and `document_id` values. Those `document_id` values match the
metadata `id` values, which is what preserves the link after CSV upload.

Null values are exported as empty CSV fields in this folder, because IT's
truncate/load process is expected to treat empty fields as SQL NULLs.
"""
    with path.open("w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"  {path.name}: IT upload instructions")


def _write_sql_header(handle, title: str) -> None:
    """Write a standard SQL file header."""
    handle.write(
        "-- =============================================================================\n"
    )
    handle.write(f"-- {title}\n")
    handle.write(
        "-- =============================================================================\n"
    )
    handle.write(f"-- Generated: {datetime.now().isoformat(timespec='seconds')}\n")
    handle.write(
        "-- Generated fields are omitted and regenerated by PostgreSQL defaults.\n"
    )
    handle.write(
        "-- =============================================================================\n\n"
    )


def _write_upsert_values(
    handle,
    table_name: str,
    columns: Sequence[str],
    row: dict[str, Any],
    column_info: dict[str, ColumnInfo],
    conflict_columns: Sequence[str],
    touch_updated_at: bool = False,
) -> None:
    """Write one INSERT ON CONFLICT statement."""
    values = [
        _format_sql_value(row.get(column), column_info.get(column))
        for column in columns
    ]
    update_columns = [column for column in columns if column not in conflict_columns]
    assignments = [
        f"    {_ident(column)} = EXCLUDED.{_ident(column)}" for column in update_columns
    ]
    if touch_updated_at:
        assignments.append(f"    {_ident('updated_at')} = CURRENT_TIMESTAMP")

    handle.write(
        f"INSERT INTO {_ident(table_name)} ({_column_sql_list(columns)})\n"
        f"VALUES ({', '.join(values)})\n"
        f"ON CONFLICT ({_column_sql_list(conflict_columns)}) DO UPDATE SET\n"
        f"{',\n'.join(assignments)};\n\n"
    )


def _write_insert_values(
    handle,
    table_name: str,
    columns: Sequence[str],
    row: dict[str, Any],
    column_info: dict[str, ColumnInfo],
) -> None:
    """Write one plain INSERT statement."""
    values = [
        _format_sql_value(row.get(column), column_info.get(column))
        for column in columns
    ]
    handle.write(
        f"INSERT INTO {_ident(table_name)} ({_column_sql_list(columns)})\n"
        f"VALUES ({', '.join(values)});\n\n"
    )


def _write_document_replacement_preamble(
    handle,
    metadata_rows: Sequence[dict[str, Any]],
) -> None:
    """Write SQL that replaces exported document rows before reimporting them."""
    handle.write(
        "CREATE TEMP TABLE _iris_import_documents (\n"
        "    db_source varchar(100) NOT NULL,\n"
        "    document_name varchar(500) NOT NULL\n"
        ") ON COMMIT DROP;\n\n"
    )

    if metadata_rows:
        handle.write("INSERT INTO _iris_import_documents (db_source, document_name)\n")
        handle.write("VALUES\n")
        values = [
            "    ("
            f"{_format_sql_value(row['db_source'], None)}, "
            f"{_format_sql_value(row['document_name'], None)}"
            ")"
            for row in metadata_rows
        ]
        handle.write(",\n".join(values))
        handle.write(";\n\n")

    handle.write(
        "DELETE FROM iris_document_chunks c\n"
        "USING iris_document_metadata m, _iris_import_documents d\n"
        "WHERE c.document_id = m.id\n"
        "  AND m.db_source = d.db_source\n"
        "  AND m.document_name = d.document_name;\n\n"
    )
    handle.write(
        "DELETE FROM iris_document_metadata m\n"
        "USING _iris_import_documents d\n"
        "WHERE m.db_source = d.db_source\n"
        "  AND m.document_name = d.document_name;\n\n"
    )


def _write_document_presence_check(handle) -> None:
    """Write SQL that fails the import if expected metadata rows are absent."""
    handle.write(
        "DO $$\n"
        "DECLARE\n"
        "    missing_documents integer;\n"
        "BEGIN\n"
        "    SELECT COUNT(*) INTO missing_documents\n"
        "    FROM _iris_import_documents d\n"
        "    LEFT JOIN iris_document_metadata m\n"
        "      ON m.db_source = d.db_source\n"
        "     AND m.document_name = d.document_name\n"
        "    WHERE m.id IS NULL;\n"
        "\n"
        "    IF missing_documents > 0 THEN\n"
        "        RAISE EXCEPTION 'Missing % metadata rows after IRIS import', missing_documents;\n"
        "    END IF;\n"
        "END $$;\n\n"
    )


def _write_chunk_insert_select(
    handle,
    chunk_columns: Sequence[str],
    row: dict[str, Any],
    column_info: dict[str, ColumnInfo],
) -> None:
    """Write one chunk INSERT that resolves regenerated document_id by natural key."""
    values = [
        _format_sql_value(row.get(column), column_info.get(column))
        for column in chunk_columns
    ]
    handle.write(
        f"INSERT INTO {_ident(CHUNKS_TABLE)} "
        f"({_column_sql_list(['document_id', *chunk_columns])})\n"
        f"SELECT m.{_ident('id')}, {', '.join(values)}\n"
        f"FROM {_ident(METADATA_TABLE)} m\n"
        f"WHERE m.{_ident('db_source')} = "
        f"{_format_sql_value(row['document_db_source'], None)}\n"
        f"  AND m.{_ident('document_name')} = "
        f"{_format_sql_value(row['document_name'], None)};\n\n"
    )


def _write_stage_table_from_target(
    handle,
    stage_name: str,
    table_name: str,
    columns: Sequence[str],
) -> None:
    """Write a temp staging table using target table column types."""
    selected_columns = ", ".join(_ident(column) for column in columns)
    handle.write(
        f"CREATE TEMP TABLE {_ident(stage_name)} AS\n"
        f"SELECT {selected_columns}\n"
        f"FROM {_ident(table_name)}\n"
        "WHERE false;\n\n"
    )


def _write_chunk_stage_table(handle, chunk_columns: Sequence[str]) -> None:
    """Write a temp staging table for chunks with document natural keys."""
    selected_columns = ",\n    ".join(f"c.{_ident(column)}" for column in chunk_columns)
    handle.write(
        "CREATE TEMP TABLE _iris_stage_chunks AS\n"
        "SELECT\n"
        "    NULL::varchar(100) AS document_db_source,\n"
        "    NULL::varchar(500) AS document_name,\n"
        f"    {selected_columns}\n"
        f"FROM {_ident(CHUNKS_TABLE)} c\n"
        "WHERE false;\n\n"
    )


def _write_copy_command(
    handle,
    stage_name: str,
    columns: Sequence[str],
    filename: str,
) -> None:
    """Write a psql copy command for a generated CSV file."""
    handle.write(
        f"\\copy {_ident(stage_name)} ({_column_sql_list(columns)}) "
        f"FROM '{filename}' WITH (FORMAT csv, HEADER true, NULL '{NULL_SENTINEL}')\n\n"
    )


def _write_registry_stage_upsert(handle, columns: Sequence[str]) -> None:
    """Write registry upsert SQL from the CSV staging table."""
    update_columns = [column for column in columns if column != "db_source"]
    assignments = [
        f"    {_ident(column)} = EXCLUDED.{_ident(column)}" for column in update_columns
    ]
    assignments.append(f"    {_ident('updated_at')} = CURRENT_TIMESTAMP")
    handle.write(
        f"INSERT INTO {_ident(REGISTRY_TABLE)} ({_column_sql_list(columns)})\n"
        f"SELECT {_column_sql_list(columns)} FROM {_ident('_iris_stage_registry')}\n"
        f"ON CONFLICT ({_ident('db_source')}) DO UPDATE SET\n"
        f"{',\n'.join(assignments)};\n\n"
    )


def _write_prompt_stage_replace(handle, columns: Sequence[str]) -> None:
    """Write prompt replacement SQL from the CSV staging table."""
    order_columns = [
        column for column in ["layer", "name", "version"] if column in columns
    ]
    order_sql = f" ORDER BY {_column_sql_list(order_columns)}" if order_columns else ""
    handle.write(
        f"DELETE FROM {_ident(PROMPTS_TABLE)} WHERE {_ident('model')} = 'iris';\n\n"
        f"INSERT INTO {_ident(PROMPTS_TABLE)} ({_column_sql_list(columns)})\n"
        f"SELECT {_column_sql_list(columns)} FROM {_ident('_iris_stage_prompts')}"
        f"{order_sql};\n\n"
    )


def _write_metadata_stage_replace(handle, columns: Sequence[str]) -> None:
    """Write document metadata replacement SQL from the CSV staging table."""
    order_columns = [
        column for column in ["db_source", "document_name"] if column in columns
    ]
    order_sql = f" ORDER BY {_column_sql_list(order_columns)}" if order_columns else ""
    handle.write(
        "CREATE TEMP TABLE _iris_import_documents AS\n"
        "SELECT db_source, document_name\n"
        "FROM _iris_stage_metadata;\n\n"
        "DELETE FROM iris_document_chunks c\n"
        "USING iris_document_metadata m, _iris_import_documents d\n"
        "WHERE c.document_id = m.id\n"
        "  AND m.db_source = d.db_source\n"
        "  AND m.document_name = d.document_name;\n\n"
        "DELETE FROM iris_document_metadata m\n"
        "USING _iris_import_documents d\n"
        "WHERE m.db_source = d.db_source\n"
        "  AND m.document_name = d.document_name;\n\n"
        f"INSERT INTO {_ident(METADATA_TABLE)} ({_column_sql_list(columns)})\n"
        f"SELECT {_column_sql_list(columns)} FROM {_ident('_iris_stage_metadata')}"
        f"{order_sql};\n\n"
    )
    _write_document_presence_check(handle)


def _write_chunk_stage_insert(handle, columns: Sequence[str]) -> None:
    """Write chunk insert SQL from the CSV staging table."""
    order_columns = [
        column
        for column in [
            "document_db_source",
            "document_name",
            "chunk_number",
            "page_number",
        ]
        if column in ["document_db_source", "document_name", *columns]
    ]
    order_sql = (
        " ORDER BY " + ", ".join(f"sc.{_ident(column)}" for column in order_columns)
        if order_columns
        else ""
    )
    selected_columns = ", ".join(f"sc.{_ident(column)}" for column in columns)
    handle.write(
        "DO $$\n"
        "DECLARE\n"
        "    missing_chunks integer;\n"
        "BEGIN\n"
        "    SELECT COUNT(*) INTO missing_chunks\n"
        "    FROM _iris_stage_chunks sc\n"
        "    LEFT JOIN iris_document_metadata m\n"
        "      ON m.db_source = sc.document_db_source\n"
        "     AND m.document_name = sc.document_name\n"
        "    WHERE m.id IS NULL;\n"
        "\n"
        "    IF missing_chunks > 0 THEN\n"
        "        RAISE EXCEPTION 'Missing document metadata for % staged chunks', missing_chunks;\n"
        "    END IF;\n"
        "END $$;\n\n"
        f"INSERT INTO {_ident(CHUNKS_TABLE)} "
        f"({_column_sql_list(['document_id', *columns])})\n"
        f"SELECT m.{_ident('id')}, {selected_columns}\n"
        "FROM _iris_stage_chunks sc\n"
        f"JOIN {_ident(METADATA_TABLE)} m\n"
        "  ON m.db_source = sc.document_db_source\n"
        " AND m.document_name = sc.document_name"
        f"{order_sql};\n\n"
    )


def _write_manifest(
    path: Path,
    settings: dict[str, str],
    table_columns: dict[str, list[ColumnInfo]],
    export_plan: dict[str, list[ColumnInfo]],
    counts: dict[str, int],
    direct_counts: dict[str, int],
    it_counts: dict[str, int],
) -> None:
    """Write machine-readable metadata describing the export."""
    payload = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "source_database": {
            "host": settings["host"],
            "port": settings["port"],
            "database": settings["database"],
            "user": settings["user"],
        },
        "counts": counts,
        "files": {
            REGISTRY_TABLE: REGISTRY_FILE,
            PROMPTS_TABLE: PROMPTS_FILE,
            METADATA_TABLE: METADATA_FILE,
            CHUNKS_TABLE: CHUNKS_FILE,
            "direct_sql": INLINE_SQL_FILE,
            "csv_import_sql": CSV_IMPORT_SQL_FILE,
        },
        "direct_table_csv_counts": direct_counts,
        "it_upload_csv_counts": it_counts,
        "exported_columns": {
            table_name: _column_names(columns)
            for table_name, columns in export_plan.items()
        },
        "generated_columns_omitted": {
            table_name: sorted(columns & set(_column_names(table_columns[table_name])))
            for table_name, columns in GENERATED_COLUMNS.items()
        },
        "direct_table_csv_columns": {
            table_name: _column_names(columns)
            for table_name, columns in table_columns.items()
        },
    }
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
        handle.write("\n")
    print(f"  {path.name}: manifest")


def _write_readme(
    path: Path,
    counts: dict[str, int],
    direct_counts: dict[str, int],
    it_counts: dict[str, int],
) -> None:
    """Write human-readable import instructions for the export directory."""
    text = f"""# Portable IRIS Export

Generated: {datetime.now().isoformat(timespec="seconds")}

## Contents

| File | Purpose |
|------|---------|
| `{INLINE_SQL_FILE}` | Self-contained SQL import. Recommended when you want one file to run. |
| `{CSV_IMPORT_SQL_FILE}` | psql loader for the CSV files in this directory. |
| `{REGISTRY_FILE}` | `{REGISTRY_TABLE}` data without generated timestamps. |
| `{PROMPTS_FILE}` | Latest `model='iris'` prompts without prompt IDs or timestamps. |
| `{METADATA_FILE}` | `{METADATA_TABLE}` data without document UUIDs or timestamps. |
| `{CHUNKS_FILE}` | `{CHUNKS_TABLE}` data without chunk UUIDs, document UUIDs, or timestamps. |
| `{IT_UPLOAD_CSV_DIR}/` | IT handoff CSVs: prompts without IDs, linked tables with IDs. |
| `{DIRECT_TABLE_CSV_DIR}/` | Exact table-shaped CSVs for direct table-by-table upload. |
| `{MANIFEST_FILE}` | Counts, source database metadata, and exported columns. |

## Row Counts

| Table | Rows |
|-------|------|
| `{REGISTRY_TABLE}` | {counts[REGISTRY_TABLE]} |
| latest `iris` prompts | {counts[PROMPTS_TABLE]} |
| `{METADATA_TABLE}` | {counts[METADATA_TABLE]} |
| `{CHUNKS_TABLE}` | {counts[CHUNKS_TABLE]} |

## Import Options

### IT Handoff CSVs

Use `{IT_UPLOAD_CSV_DIR}/` for the current IT process:

- `{PROMPTS_FILE}` has latest `model='iris'` prompts without IDs or timestamps.
- `{REGISTRY_FILE}` is table-shaped for truncate/load.
- `{METADATA_FILE}` is table-shaped and includes document `id` UUIDs.
- `{CHUNKS_FILE}` is table-shaped and includes both chunk `id` UUIDs and
  `document_id` values that match `{METADATA_TABLE}.id`.

IT CSV row counts:

| Table | Rows |
|-------|------|
| `{REGISTRY_TABLE}` | {it_counts[REGISTRY_TABLE]} |
| latest `iris` prompts | {it_counts[PROMPTS_TABLE]} |
| `{METADATA_TABLE}` | {it_counts[METADATA_TABLE]} |
| `{CHUNKS_TABLE}` | {it_counts[CHUNKS_TABLE]} |

### Direct Table CSV Upload

Use `{DIRECT_TABLE_CSV_DIR}/` if the destination process uploads CSVs directly
into the target tables one by one. These files preserve source UUIDs so
`iris_document_chunks.document_id` still points to the matching
`iris_document_metadata.id` after upload.

Upload order:

1. `{REGISTRY_TABLE}`
2. `{PROMPTS_TABLE}`
3. `{METADATA_TABLE}`
4. `{CHUNKS_TABLE}`

After loading prompts with preserved IDs, run:

```bash
psql -h <host> -p <port> -d <database> -U <user> -f {DIRECT_TABLE_CSV_DIR}/{DIRECT_UPLOAD_SQL_FILE}
```

Direct CSV row counts:

| Table | Rows |
|-------|------|
| `{REGISTRY_TABLE}` | {direct_counts[REGISTRY_TABLE]} |
| latest `iris` prompts | {direct_counts[PROMPTS_TABLE]} |
| `{METADATA_TABLE}` | {direct_counts[METADATA_TABLE]} |
| `{CHUNKS_TABLE}` | {direct_counts[CHUNKS_TABLE]} |

### Regenerated IDs

Use the root-level SQL files below only if the destination should regenerate
prompt IDs, document UUIDs, chunk UUIDs, and timestamp columns.

Direct SQL:

```bash
psql -h <host> -p <port> -d <database> -U <user> -f {INLINE_SQL_FILE}
```

CSV staging:

```bash
cd <this-export-directory>
psql -h <host> -p <port> -d <database> -U <user> -f {CSV_IMPORT_SQL_FILE}
```

## Generated Fields

The `direct_table_csv/` files preserve source UUIDs and timestamps. That is what
makes direct table-by-table CSV upload work for the linked document tables.

The root-level regenerated-ID files intentionally omit generated fields so the
destination PostgreSQL database creates destination-local values. `prompts.id`,
document UUIDs, chunk UUIDs, and timestamp columns are not copied from the source
environment in that import mode.

Chunks are exported with `document_db_source` and `document_name`. The import SQL
uses those fields to look up the regenerated `iris_document_metadata.id` values
and populate `iris_document_chunks.document_id`.
"""
    with path.open("w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"  {path.name}: instructions")


def _format_csv_value(
    value: Any,
    column_info: ColumnInfo | None,
    null_value: str = NULL_SENTINEL,
) -> str:
    """Format a database value for CSV export."""
    if value is None:
        return null_value
    if column_info and _is_json_column(column_info):
        return _json_text(value)
    if column_info and _is_array_column(column_info):
        return _pg_array_literal(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (datetime, date, time)):
        return value.isoformat()
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, bytes):
        return _bytes_to_text(value)
    return str(value)


def _format_sql_value(value: Any, column_info: ColumnInfo | None) -> str:
    """Format a database value as a PostgreSQL literal."""
    if value is None:
        return "NULL"
    if column_info and _is_json_column(column_info):
        return f"{_quote_sql_string(_json_text(value))}::{column_info.udt_name}"
    if column_info and _is_array_column(column_info):
        return f"{_quote_sql_string(_pg_array_literal(value))}::{_array_sql_type(column_info)}"
    if column_info and _is_vector_column(column_info):
        return f"{_quote_sql_string(str(value))}::{column_info.udt_name}"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float, Decimal)) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, (datetime, date, time)):
        return _quote_sql_string(value.isoformat())
    if isinstance(value, bytes):
        return _quote_sql_string(_bytes_to_text(value))
    return _quote_sql_string(str(value))


def _json_text(value: Any) -> str:
    """Render a JSON-compatible value as compact JSON text."""
    if isinstance(value, str):
        return value
    return json.dumps(
        value,
        default=_json_default,
        ensure_ascii=False,
        separators=(",", ":"),
    )


def _json_default(value: Any) -> str:
    """Convert non-standard JSON values used by psycopg2."""
    if isinstance(value, (datetime, date, time)):
        return value.isoformat()
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, bytes):
        return _bytes_to_text(value)
    raise TypeError(f"Object is not JSON serializable: {type(value)!r}")


def _pg_array_literal(value: Any) -> str:
    """Render a Python or PostgreSQL array value as a PostgreSQL array literal."""
    if isinstance(value, str):
        return value
    if value is None:
        return "{}"
    rendered = []
    for item in value:
        if item is None:
            rendered.append("NULL")
            continue
        text = str(item)
        escaped = text.replace("\\", "\\\\").replace('"', '\\"')
        needs_quotes = (
            escaped == ""
            or escaped.upper() == "NULL"
            or any(char in escaped for char in [",", "{", "}", '"', "\\"])
            or any(char.isspace() for char in escaped)
        )
        rendered.append(f'"{escaped}"' if needs_quotes else escaped)
    return "{" + ",".join(rendered) + "}"


def _quote_sql_string(value: str) -> str:
    """Quote and escape a PostgreSQL string literal."""
    return "'" + value.replace("'", "''") + "'"


def _bytes_to_text(value: bytes) -> str:
    """Decode bytes as UTF-8 or hex when text decoding fails."""
    try:
        return value.decode("utf-8")
    except UnicodeDecodeError:
        return value.hex()


def _array_sql_type(column_info: ColumnInfo) -> str:
    """Return a PostgreSQL type cast for an array column."""
    if column_info.udt_name in ARRAY_TYPE_CASTS:
        return ARRAY_TYPE_CASTS[column_info.udt_name]
    if column_info.udt_name.startswith("_"):
        return f"{column_info.udt_name[1:]}[]"
    return "text[]"


def _is_json_column(column_info: ColumnInfo) -> bool:
    """Return whether a column uses PostgreSQL JSON storage."""
    return column_info.udt_name in {"json", "jsonb"} or column_info.data_type in {
        "json",
        "jsonb",
    }


def _is_array_column(column_info: ColumnInfo) -> bool:
    """Return whether a column uses a PostgreSQL array type."""
    return column_info.data_type == "ARRAY" or column_info.udt_name.startswith("_")


def _is_vector_column(column_info: ColumnInfo) -> bool:
    """Return whether a column uses a pgvector-compatible vector type."""
    return column_info.udt_name in {"vector", "halfvec", "sparsevec"}


def _column_names(columns: Sequence[ColumnInfo]) -> list[str]:
    """Return column names from column metadata."""
    return [column.name for column in columns]


def _column_map(columns: Sequence[ColumnInfo]) -> dict[str, ColumnInfo]:
    """Return column metadata keyed by column name."""
    return {column.name: column for column in columns}


def _chunk_csv_columns(columns: Sequence[ColumnInfo]) -> list[str]:
    """Return CSV columns for chunks, including document natural keys."""
    return ["document_db_source", "document_name", *_column_names(columns)]


def _column_sql_list(columns: Sequence[str]) -> str:
    """Return a comma-separated SQL identifier list."""
    return ", ".join(_ident(column) for column in columns)


def _ident(identifier: str) -> str:
    """Quote a PostgreSQL identifier."""
    return '"' + identifier.replace('"', '""') + '"'


if __name__ == "__main__":
    main()
